CREATE TABLE "Users" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "Name" varchar(30) NOT NULL,
  "Email" varchar(50) NOT NULL,
  "Password" varchar(20) NOT NULL,
  "Age" int NOT NULL,
  "Roles_id" int NOT NULL
);

CREATE TABLE "Users_Courses" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "student" int NOT NULL,
  "course_id" int NOT NULL
);

CREATE TABLE "Courses" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "Title" varchar(50) NOT NULL,
  "Description" text NOT NULL,
  "Level_id" int NOT NULL,
  "Teacher" int NOT NULL,
  "Category_id" int NOT NULL
);

CREATE TABLE "Course_Videos" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "Title" varchar(30) NOT NULL,
  "Url" varchar(30) NOT NULL,
  "Couses_id" int NOT NULL
);

CREATE TABLE "Categories" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "Name" varchar(30) NOT NULL
);

CREATE TABLE "Roles" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "Name" varchar(30) NOT NULL
);

CREATE TABLE "levels" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "Level" varchar(30) NOT NULL
);

ALTER TABLE "Users_Courses" ADD FOREIGN KEY ("student") REFERENCES "Users" ("id");

ALTER TABLE "Users_Courses" ADD FOREIGN KEY ("course_id") REFERENCES "Courses" ("id");

ALTER TABLE "Users" ADD FOREIGN KEY ("Roles_id") REFERENCES "Roles" ("id");

ALTER TABLE "Courses" ADD FOREIGN KEY ("Category_id") REFERENCES "Categories" ("id");

ALTER TABLE "Course_Videos" ADD FOREIGN KEY ("Couses_id") REFERENCES "Courses" ("id");

ALTER TABLE "Courses" ADD FOREIGN KEY ("Level_id") REFERENCES "levels" ("id");

ALTER TABLE "Courses" ADD FOREIGN KEY ("Teacher") REFERENCES "Users" ("id");



postgres=# CREATE DATABASE courses;

postgres=# \c courses;

courses=# INSERT INTO "Roles" ("Name") VALUES ('Student', 'Teacher', 'Admin');

courses=# INSERT INTO level ("Level") VALUES ('Beginner', 'Advanced', 'Expert');

courses=# INSERT INTO "Categories" ("Name") VALUES ('Dev Backend', 'Dev Frontend');

courses=# INSERT INTO "Users" ("Name", "Email", "Password", "Age", "Roles_id") VALUES ('Anderson', 'annderson@gmail.com', 'user1234', 22, 1);

courses=# INSERT INTO "Users" ("Name", "Email", "Password", "Age", "Roles_id") VALUES ('Rances', 'rances@gmail.com', 'user1234', 42, 3);

courses=# INSERT INTO "Users" ("Name", "Email", "Password", "Age", "Roles_id") VALUES ('Perla', 'perla@gmail.com', 'user1234', 24, 1);

courses=# INSERT INTO "Users" ("Name", "Email", "Password", "Age", "Roles_id") VALUES ('Ian', 'ian@gmail.com', 'user1234', 32, 2);

courses=# INSERT INTO "Users" ("Name", "Email", "Password", "Age", "Roles_id") VALUES ('Federico', 'federico@gmail.com', 'user1234', 37, 1);

courses=# INSERT INTO "Courses" ("Title", "Description", "Level_id", "Teacher", "Category_id") VALUES ('Node.js', 'Desarrollo Backend', 2, 5, 1);

courses=# INSERT INTO "Courses" ("Title", "Description", "Level_id", "Teacher", "Category_id") VALUES ('Fundamentos', 'HTML, CSS, JavaScript', 1, 5, 2);

courses=# INSERT INTO "Courses" ("Title", "Description", "Level_id", "Teacher", "Category_id") VALUES ('Desarrollo Pro', 'React', 3, 5, 2);

courses=# INSERT INTO "Course_Videos" ("Title", "Url", "Couses_id") VALUES ('React-Redux', 'www.courses.com', 3);

courses=# INSERT INTO "Course_Videos" ("Title", "Url", "Couses_id") VALUES ('Introducion a JavaScript', 'www.courses.com', 2);

courses=# INSERT INTO "Course_Videos" ("Title", "Url", "Couses_id") VALUES ('Comandos SQL', 'www.courses.com', 1);











